### ISSUE TITLE
Strict restrictions on the master port parameter

### ISSUE THREAD

**Issue by avinashmeda** [ywilkof/spark-jobs-rest-client#14]
Hi,
The masterPort cannot be reset by setting it to null. The reason why there should be no hard check on the master port is that when the master is mesos we have proxies defined and hence the ports are dynamic. We usually create virtual host proxies and point to the label only(behaves as host). So if it's possible to remove that hard check on the master port being null in the SparkRestClient and also consider this in the getMasterUrl function it would help submitting apps to mesos which runs the spark as a service(mesos dispatcher hence)

Thanks,
Avinash

**Comment by ywilkof** [comment]
Hi @avinashmeda,
According to the [Spark documentation](https://spark.apache.org/docs/latest/submitting-applications.html#master-urls), the master URL with mesos has to be of the form _mesos://HOST:PORT,_ also with [mesos dispatcher](https://spark.apache.org/docs/latest/running-on-mesos.html#cluster-mode). Can you confirm that submitting just with host and no port is working?

**Comment by avinashmeda** [comment]
Yes

**Comment by ywilkof** [comment]
Could you please provide the CURL command example that you used and worked for you?

**Comment by avinashmeda** [comment]
I executed the spark rest url directly. This is what that worked for me

URL: http://[host]:[port]/v1/submissions/create
METHOD : POST
REQUEST BODY : 
{
  "action": "CreateSubmissionRequest",
  "appResource": "http://*****:8090/jar/examples.jar",
  "appArgs": [
    "1000"
  ],
  "clientSparkVersion": "2.1.0",
  "mainClass": "org.apache.spark.examples.SparkPi",
  "environmentVariables": {
    "JAVA_HOME": "/opt/mesosphere/active/java/usr/java"
  },
  "sparkProperties": {
    "spark.app.name": "Sparkpi",
    "spark.master": "mesos://spark.pqa.*******.space"
  }
}

**Comment by avinashmeda** [comment]
Hello,
Any updates ?  Let me know if you need more information.

Thanks,
Avinash

**Comment by ywilkof** [comment]
Hi,
The example you provided is providing the needed information.
I would get to this on the weekend!

**Comment by avinashmeda** [comment]
Thanks :)

**Comment by ywilkof** [comment]
https://github.com/ywilkof/spark-jobs-rest-client/pull/16
Have a look and tell me if this will solve your issue

**Comment by avinashmeda** [comment]
Thanks. I have seen the changes and that's exactly what we would have liked

**Comment by ywilkof** [comment]
version 1.3.4 incorporating this change should be available on maven central soon.
