### ISSUE TITLE
can't build it

### ISSUE THREAD

**Issue by leonsoft** [ywilkof/spark-jobs-rest-client#18]
`
Description	Resource	Path	Location	Type
The method builder() is undefined for the type JobSubmitRequest	JobSubmitRequestSpecificationImpl.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 125	Java Problem
The method builder() is undefined for the type JobSubmitRequest.SparkProperties	JobSubmitRequestSpecificationImpl.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 133	Java Problem
The method getClient() is undefined for the type SparkRestClient	JobStatusRequestSpecificationImpl.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 40	Java Problem
The method getClient() is undefined for the type SparkRestClient	JobSubmitRequestSpecificationImpl.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 154	Java Problem
The method getClient() is undefined for the type SparkRestClient	KillJobRequestSpecificationImpl.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 26	Java Problem
The method getClusterMode() is undefined for the type SparkRestClient	JobSubmitRequestSpecificationImpl.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 136	Java Problem
The method getDriverState() is undefined for the type JobStatusResponse	JobStatusRequestSpecificationImpl.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 25	Java Problem
The method getEnvironmentVariables() is undefined for the type SparkRestClient	JobSubmitRequestSpecificationImpl.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 131	Java Problem
The method getSparkVersion() is undefined for the type SparkRestClient	JobSubmitRequestSpecificationImpl.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 129	Java Problem
The method getSubmissionId() is undefined for the type SparkResponse	JobSubmitRequestSpecificationImpl.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 159	Java Problem
The method getSuccess() is undefined for the type JobStatusResponse	JobStatusRequestSpecificationImpl.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 41	Java Problem
The method getSuccess() is undefined for the type SparkResponse	JobSubmitRequestSpecificationImpl.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 156	Java Problem
The method releaseConnection() is undefined for the type HttpRequestBase	HttpRequestUtil.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 23	Java Problem
The method setAction(Action) is undefined for the type JobStatusResponse	SparkRestClientMockServerTest.java	/spark-jobs-rest-client/src/test/java/com/github/ywilkof/sparkrestclient	line 293	Java Problem
The method setClient(HttpClient) is undefined for the type SparkRestClient	SparkRestClient.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 174	Java Problem
The method setClusterMode(ClusterMode) is undefined for the type SparkRestClient	SparkRestClient.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 175	Java Problem
The method setDriverState(DriverState) is undefined for the type JobStatusResponse	SparkRestClientMockServerTest.java	/spark-jobs-rest-client/src/test/java/com/github/ywilkof/sparkrestclient	line 294	Java Problem
The method setEnvironmentVariables(Map<String,String>) is undefined for the type SparkRestClient	SparkRestClient.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 173	Java Problem
The method setMasterApiRoot(String) is undefined for the type SparkRestClient	SparkRestClient.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 172	Java Problem
The method setMasterApiRoot(String) is undefined for the type SparkRestClient	SparkRestClientTest.java	/spark-jobs-rest-client/src/test/java/com/github/ywilkof/sparkrestclient	line 14	Java Problem
The method setMasterApiRoot(String) is undefined for the type SparkRestClient	SparkRestClientTest.java	/spark-jobs-rest-client/src/test/java/com/github/ywilkof/sparkrestclient	line 34	Java Problem
The method setMasterHost(String) is undefined for the type SparkRestClient	SparkRestClient.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 171	Java Problem
The method setMasterHost(String) is undefined for the type SparkRestClient	SparkRestClientTest.java	/spark-jobs-rest-client/src/test/java/com/github/ywilkof/sparkrestclient	line 16	Java Problem
The method setMasterHost(String) is undefined for the type SparkRestClient	SparkRestClientTest.java	/spark-jobs-rest-client/src/test/java/com/github/ywilkof/sparkrestclient	line 25	Java Problem
The method setMasterHost(String) is undefined for the type SparkRestClient	SparkRestClientTest.java	/spark-jobs-rest-client/src/test/java/com/github/ywilkof/sparkrestclient	line 35	Java Problem
The method setMasterHost(String) is undefined for the type SparkRestClient	SparkRestClientTest.java	/spark-jobs-rest-client/src/test/java/com/github/ywilkof/sparkrestclient	line 44	Java Problem
The method setMasterPort(int) is undefined for the type SparkRestClient	SparkRestClientTest.java	/spark-jobs-rest-client/src/test/java/com/github/ywilkof/sparkrestclient	line 15	Java Problem
The method setMasterPort(int) is undefined for the type SparkRestClient	SparkRestClientTest.java	/spark-jobs-rest-client/src/test/java/com/github/ywilkof/sparkrestclient	line 24	Java Problem
The method setMasterPort(Integer) is undefined for the type SparkRestClient	SparkRestClient.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 170	Java Problem
The method setServerSparkVersion(String) is undefined for the type JobStatusResponse	SparkRestClientMockServerTest.java	/spark-jobs-rest-client/src/test/java/com/github/ywilkof/sparkrestclient	line 296	Java Problem
The method setSparkVersion(String) is undefined for the type SparkRestClient	SparkRestClient.java	/spark-jobs-rest-client/src/main/java/com/github/ywilkof/sparkrestclient	line 169	Java Problem
The method setSubmissionId(String) is undefined for the type JobStatusResponse	SparkRestClientMockServerTest.java	/spark-jobs-rest-client/src/test/java/com/github/ywilkof/sparkrestclient	line 295	Java Problem
The method setSuccess(boolean) is undefined for the type JobStatusResponse	SparkRestClientMockServerTest.java	/spark-jobs-rest-client/src/test/java/com/github/ywilkof/sparkrestclient	line 297	Java Problem
The method setWorkerHostPort(String) is undefined for the type JobStatusResponse	SparkRestClientMockServerTest.java	/spark-jobs-rest-client/src/test/java/com/github/ywilkof/sparkrestclient	line 298	Java Problem
The method setWorkerId(String) is undefined for the type JobStatusResponse	SparkRestClientMockServerTest.java	/spark-jobs-rest-client/src/test/java/com/github/ywilkof/sparkrestclient	line 299	Java Problem
`

**Comment by ywilkof** [comment]
Hi @leonsoft,
 You need to install the lombok plugin for your IDE.

**Comment by leonsoft** [comment]
Got it ...thanks.
