### ISSUE TITLE
Possible to add a new status for NOT_FOUND ?

### ISSUE THREAD

**Issue by avneet15** [ywilkof/spark-jobs-rest-client#19]
Currently for Spark 2.1 ,if we try to GET the status for a non-existing job, the status returned by the internal REST API is "NOT_FOUND", but this status is not listed in the enum for possible DriverState's.
Due to this, the library bubbles up a "FailedSparkRequestException", which is not differentiable from other errors. 
Would it be possible to add this as a possible DriverState, so we can differentiate Job not found vs other errors ?

**Comment by ywilkof** [comment]
NOT_FOUND added. A new release (1.3.5)  should be available soon on Maven.

**Comment by avneet15** [comment]
Thanks, but it doesn't resolve the issue, as a FailedSparkRequestException is still thrown due to "success" field being false:https://github.com/ywilkof/spark-jobs-rest-client/blob/master/src/main/java/com/github/ywilkof/sparkrestclient/JobStatusRequestSpecificationImpl.java#L41.

So an extra condition there will be needed.

**Comment by avneet15** [comment]
Hey,any update on this ?

**Comment by mahmoudparsian** [comment]
I just had a shoulder surgery: has made me slow on my end of tasks, please give me 2-3 weeks to recover and get my energy and movement.
I will look into this soon.

Thanks for your patience.

best regards,
Mahmoud

**Comment by avneet15** [comment]
No worries..wish you a speedy recovery !

**Comment by ywilkof** [comment]
Solved in https://github.com/ywilkof/spark-jobs-rest-client/pull/21
