### ISSUE TITLE
Master port optional

### ISSUE THREAD

**Issue by avneet15** [ywilkof/spark-jobs-rest-client#22]
Currently, an optional port of 6066 is appended to the URL for talking to the Spark service.
There is a use-case in which the port is completely missing, and only the host is needed.

Is this a feature which could be supported? I could add a PR for it then.

**Comment by avneet15** [comment]
@ywilkof Any comment on this?

**Comment by ywilkof** [comment]
Hi @avneet15 , this should already be possible, as it was adde in https://github.com/ywilkof/spark-jobs-rest-client/issues/14.
