### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by avneet15** [ywilkof/spark-jobs-rest-client#23]
@ywilkof  Could I submit a PR to optionally support https Spark url's ?

**Comment by avneet15** [comment]
@ywilkof Thoughts?

**Comment by ywilkof** [comment]
Hi @avneet15,
The client allows you to supply your own client, which you can configure for SSL support. Doesn't that solve your requirement?

**Comment by avneet15** [comment]
I actually need to access an https url here:
https://github.com/ywilkof/spark-jobs-rest-client/blob/499c38ceda516fcd00db87f3342ec0d6f6453699/src/main/java/com/github/ywilkof/sparkrestclient/JobSubmitRequestSpecificationImpl.java#L142

**Comment by ywilkof** [comment]
@avneet15 
Does this answer your requirement? 
https://github.com/ywilkof/spark-jobs-rest-client/commit/7dcead2795dba151d43c09744eab1bea7f6b863e

**Comment by avneet15** [comment]
@ywilkof Yes, this is what I'm looking for, thanks!

**Comment by ywilkof** [comment]
Closing this issue then. A new version will be available on Maven Central soon.
