### ISSUE TITLE
Result of spark job

### ISSUE THREAD

**Issue by aminaaslam** [ywilkof/spark-jobs-rest-client#5]
Hi @ywilkof, Once the job is submitted. How can get the result of the job, i am not talking about the status; i know how to get that. Does your api return something like this? i am interested in the result object.

{
  "duration": "6.341 secs",
  "classPath": "spark.jobserver.WordCountExample",
  "startTime": "2015-10-16T03:17:03.127Z",
  "context": "b7ea0eb5-spark.jobserver.WordCountExample",
  "result": {
    "a": 2,
    "b": 2,
    "c": 1,
    "see": 1
  },
  "status": "FINISHED",
  "jobId": "5453779a-f004-45fc-a11d-a39dae0f9bf4"
}⏎

**Comment by ywilkof** [comment]
Hi @aminaaslam ,
This scenario is not covered as part of this project, as this requires a process to wait for the result, and this is aclient which only sends single HTTP requests with no sessions or contexts. This is however covered in the scope of the [Job Server](https://github.com/spark-jobserver/spark-jobserver), by sending requests with the sync=true flag. You will have to set up the server and change your job to implement their traits.
